# ===============================
# Server Configuration
# ===============================
server.port=8080

# ===============================
# MySQL Database Configuration
# ===============================
spring.datasource.url=JDBC:mysql://localhost:3306/testdb
spring.datasource.username=root
spring.datasource.password=Siddhi#123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Redis connection
spring.redis.host=localhost
spring.redis.port=6379
spring.cache.type=redis

#ElasticSearch
spring.elasticsearch.uris=http://localhost:9200
spring.data.elasticsearch.repositories.enabled=true
spring.data.elasticsearch.auto-create-index=false
